# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  commands:
    # Install uv and sync dependencies from uv.lock
    - pip install uv
    - uv sync --frozen
    - uv run sphinx-build -b html docs $READTHEDOCS_OUTPUT/html

# Build documentation from the docs/ directory using Sphinx
sphinx:
  configuration: docs/conf.py

# Notes:
# - We rely on uv.lock for reproducible dependency resolution.
# - The old-style `python.install` block using requirements.txt is no longer viable
#   as we don't have that file checked in anymore.
# - Use `uv export --locked --format=requirements-txt` to generate such a file
#   if a pip-compatible file is ever required, e.g. for environments without uv.
